apiVersion: v1
kind: Service
metadata:
  name: trendify-service
  namespace: trendify
  labels:
    app: trendify
spec:
  selector:
    app: trendify
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
